### ISSUE TITLE
boost-python does not build 

### ISSUE THREAD

**Issue by kyungyunlee** [ethman/slakh-generation#5]
Hi, I am trying to install boost-python for renderman, but I get "Error: boost-python has been disabled because it does not build!". Any support for python3 coming soon ? Thank you!

**Comment by ethman** [comment]
Hey kyungyun, thanks for checking out the project. Unfortunately, I have no plans to get this working with python3. I just don't have the time to do it. However, if you want to add python3 support, please add a PR and I'll be happy to review it. You should also check out another project, [DawDreamer](https://github.com/DBraun/DawDreamer), which is actively supported (i.e., works in python3). Another project to be aware of is [Pedalboard by Spotify](https://github.com/spotify/pedalboard).

**Comment by kyungyunlee** [comment]
@ethman Hi Ethan, thanks so much! I did come across dawdreamer shortly after commenting here and it works well for me! 👍
